message: Dev environment test data
exception: false

server:
  port: 8981

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl: 
#       defaultZone: ${EUREKA_URI:http://localhost:8982/eureka}
#  instance:
#    preferIpAddress: true

management:
    security: 
      enabled: false
    endpoints: 
      web: 
       exposure: 
        include: '*' 
