server:
  port: 8080
  
spring:
  application:
    name: gateway-zuul
  
eureka:
  client:
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:8982/eureka}
  instance:
    preferIpAddress: true
    
management:
    security: 
      enabled: false
    endpoints: 
      web: 
       exposure: 
        include: '*' 
  
