server:
  port: 8080
  
spring:
  application:
    name: gateway-zuul
  
eureka:
  client:
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:8982/eureka}
  instance:
    preferIpAddress: true
    
zuul:
  routes:
    sidecar:
      path: /service/**
      serviceId: sidecar
    sidecar1:
      path: /product-service/**
      serviceId: sidecar1
      
hystrix:
  command:
    sidecar:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker: 
        requestVolumeThreshold: 5
        errorThresholdPercentage: 10
        sleepWindowInMilliseconds: 5000
      metrics: 
        rollingStats: 
          timeInMilliseconds: 30000
    sidecar1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    
management:
    security: 
      enabled: false
    endpoints: 
      web: 
       exposure: 
        include: '*' 
  
